# Generated by Django 4.1 on 2022-12-02 01:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=25, null=True)),
                ('lastName', models.CharField(max_length=25, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('phoneNumber', models.CharField(max_length=13, null=True)),
                ('address', models.TextField(max_length=200, null=True)),
                ('officeEmail', models.EmailField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
