# Generated by Django 4.1 on 2022-12-02 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='firstName',
            new_name='first_Name',
        ),
    ]
