# Generated by Django 4.1 on 2022-11-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_address_profile_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstName',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
