# Generated by Django 4.1 on 2022-11-27 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_firstname_profile_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
