# Generated by Django 4.1 on 2022-11-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_officeemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='officeEmail',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
