# Generated by Django 4.1 on 2022-11-28 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_officeemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phoneNumber',
            field=models.TextField(max_length=13, null=True),
        ),
    ]
