# Generated by Django 4.1 on 2022-11-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='propertyDescription',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='propertyName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='propertyNeighborhood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='propertyPrice',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
