# Generated by Django 4.1 on 2022-11-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0004_alter_listing_propertydescription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='propertyDescription',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
