# Generated by Django 4.1 on 2022-11-28 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0005_alter_listing_propertydescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='propertyImage',
        ),
        migrations.AlterField(
            model_name='listing',
            name='propertyDescription',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=10, null=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='listings_pics')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realtor.listing')),
            ],
        ),
    ]
