# Generated by Django 4.1 on 2022-12-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0007_listing_propertyimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='propertyImage',
            field=models.FileField(upload_to=''),
        ),
    ]
