# Generated by Django 4.1 on 2022-12-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0009_alter_listing_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featuredProperty',
            field=models.BooleanField(default=False),
        ),
    ]
