# Generated by Django 4.1 on 2022-12-03 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0011_alter_listing_featuredproperty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='featuredProperty',
            field=models.BooleanField(default=False),
        ),
    ]
