# Generated by Django 4.1 on 2022-12-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0012_alter_listing_featuredproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='propertyAddress',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='propertyType',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
