# Generated by Django 4.1 on 2022-12-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtor', '0013_listing_propertyaddress_listing_propertytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='propertyStatus',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
